# Site settings
title: Central Ohio Trails
email: contactmichaelbuckley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Find the best running trails, cycling trails, trail running trails,
  and mountain biking trails in the Columbus, Ohio metro area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.centralohiotrails.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""
permalink: pretty

# Build settings
markdown: kramdown
